/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PortInfo struct {
	Id string `json:"id,omitempty"`
	FixedIPs []string `json:"fixedIPs,omitempty"`
}
