/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Loại GPU
type InstanceGpuTypeInfo struct {
	// Id loại GPU
	Id int32 `json:"id,omitempty"`
	// Tên loại GPU
	Name string `json:"name"`
}
