/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ImageInfo struct {
	Name string `json:"name,omitempty"`
	Versions []ImageVersionInfo `json:"versions,omitempty"`
}
