/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SecurityGroupInfo struct {
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
}
