/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SnapshotInfo struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
