/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InstanceEditModel struct {
	// Id máy ảo sẽ điều chỉnh
	InstanceId int32 `json:"instanceId,omitempty"`
	// Id hệ điều hành mới
	NewImageId int32 `json:"newImageId,omitempty"`
}
