/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IpPublicInfo struct {
	Id int32 `json:"id,omitempty"`
	IpAddress string `json:"ipAddress,omitempty"`
	IPv6Address string `json:"iPv6Address,omitempty"`
}
