/*
 * Public API - Development
 *
 * Public API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VlanInfo struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	SubnetAddressRequired string `json:"subnetAddressRequired,omitempty"`
}
